version: "3.7"
services:
    invdb-ms:
        image: 015137877991.dkr.ecr.us-east-1.amazonaws.com/invdb-ms:${BUILD_NUMBER}
        environment:
            - SPRING_PROFILES_ACTIVE=test
        deploy:
            restart_policy:
                condition: any
                max_attempts: 3
                window: 5m
            mode: replicated
            replicas: 1
            # placement:
            #     constraints:
            #         - node.hostname == ghg-test
            update_config:
                order: start-first
                parallelism: 1
                delay: 5m
#            labels:
#                - traefik.enable=true
#                - traefik.docker.network=eggrt
#                - traefik.port=8080
#                - traefik.frontend.rule=PathPrefix:/invdb-ms
        ports:
            - "6780:8080"
#        networks:
#            - eggrt
#networks:
#    eggrt:
#        external: true
